// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"obs-scheduler/internal/config"
	"obs-scheduler/internal/domain"
	"obs-scheduler/internal/infrastructure/lifecycle"
	"obs-scheduler/internal/infrastructure/obs"
	"obs-scheduler/internal/usecase"
)

// Injectors from wire.go:

func InitializeScheduler(cfg *config.Config) (*usecase.Scheduler, func(), error) {
	client := provideOBSClient(cfg)
	appLifecycle := provideOBSApp(cfg)
	bool2 := provideSkipLaunch(cfg)
	scheduler := usecase.NewScheduler(client, appLifecycle, bool2)
	return scheduler, func() {
	}, nil
}

// wire.go:

func provideOBSClient(cfg *config.Config) *obs.Client {
	return obs.NewClient(cfg.Addr, cfg.Password)
}

func provideOBSApp(cfg *config.Config) domain.AppLifecycle {
	return lifecycle.NewOBSApp(cfg.OBSAppName, cfg.OBSAppPath)
}

func provideSkipLaunch(cfg *config.Config) bool {
	return cfg.SkipLaunch
}
