// Code generated by MockGen. DO NOT EDIT.
// Source: lifecycle.go
//
// Generated by this command:
//
//	mockgen -source=lifecycle.go -destination=../mock/mock_lifecycle.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAppLifecycle is a mock of AppLifecycle interface.
type MockAppLifecycle struct {
	ctrl     *gomock.Controller
	recorder *MockAppLifecycleMockRecorder
	isgomock struct{}
}

// MockAppLifecycleMockRecorder is the mock recorder for MockAppLifecycle.
type MockAppLifecycleMockRecorder struct {
	mock *MockAppLifecycle
}

// NewMockAppLifecycle creates a new mock instance.
func NewMockAppLifecycle(ctrl *gomock.Controller) *MockAppLifecycle {
	mock := &MockAppLifecycle{ctrl: ctrl}
	mock.recorder = &MockAppLifecycleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppLifecycle) EXPECT() *MockAppLifecycleMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockAppLifecycle) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockAppLifecycleMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAppLifecycle)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockAppLifecycle) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockAppLifecycleMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAppLifecycle)(nil).Stop), ctx)
}
